---
# tasks file for freeswitch-mw
#- name: Add FreeSwitch apt repository (1.4)
#  apt_repository: repo='deb http://files.freeswitch.org/repo/deb/debian/ wheezy main'

#- name: Add FreeSwitch Repo Signing key
#  apt_key: url=http://files.freeswitch.org/repo/deb/debian/freeswitch_archive_g0.pub

#- name: Install FreeSwitch server
#  action: apt name=freeswitch-meta-vanilla update_cache=yes

# Installation from sources
- name: Install FreeSwitch dependencies
  apt: name={{ item }} update_cache=yes
  with_items:
   - autoconf
   - automake
   - devscripts
   - gawk
   - g++
   - git-core
   - libjpeg-dev
   - libncurses5-dev
   - libtool
   - make
   - python-dev
   - gawk
   - pkg-config
   - libtiff5-dev
   - libperl-dev
   - libgdbm-dev
   - libdb-dev
   - gettext
   - libssl-dev
   - libcurl4-openssl-dev
   - libpcre3-dev
   - libspeex-dev
   - libspeexdsp-dev
   - libsqlite3-dev
   - libedit-dev
   - libldns-dev
   - libpq-dev
   
- name: Specific Debian flavored systems"
  apt: name={{ item }} update_cache=yes
  with_items:
   - libtool-bin
  when: (ansible_distribution == "Debian" and ansible_distribution_major_version == "7") or
        (ansible_distribution == "Debian" and ansible_distribution_major_version == "8")

- name: Install FreeSwitch source code
  git: repo=https://freeswitch.org/stash/scm/fs/freeswitch.git
       dest={{freeswitch_sources_path}}
       version={{freeswitch_version}}

- name: bootstrap - take a coffee - it takes time --
  shell: ./bootstrap.sh -j chdir={{freeswitch_sources_path}}

- name: copy template modules file
  copy: src={{freeswitch_modules_template}} dest=/usr/src/freeswitch/modules.conf backup=yes

- name: Freeswitch configuration
  shell: ./{{freeswitch_configure_command}} chdir={{freeswitch_sources_path}}

- name: FreeSwitch make - another coffee ! --
  shell: make chdir={{freeswitch_sources_path}}

- name: FreeSwitch install
  shell: make install chdir={{freeswitch_sources_path}}

- name: FreeSwitch install sounds
  shell: make cd-sounds-install cd-moh-install chdir={{freeswitch_sources_path}}

- name: Add user "freeswitch"
  user: name={{freeswitch_owner}} group={{freeswitch_group}} home={{freeswitch_path}}

- name: Change ownership of FreeSwitch installation
  file: path={{freeswitch_path}} owner={{freeswitch_owner}} group={{freeswitch_group}} mode="ug=rwX,o=" state=directory recurse=yes

- name: Change ownership of FreeSwitch binary files
  file: path={{freeswitch_path}}bin/ owner={{freeswitch_owner}} group={{freeswitch_group}} mode="u=rwx,g=rx" state=directory recurse=yes

- name: Create /var/lib/freeswitch
  file: path=/var/lib/freeswitch owner={{freeswitch_owner}} group={{freeswitch_group}} mode="u=rwx,o=" state=directory recurse=yes

- name: copy init script
  copy: src={{freeswitch_init_template}} dest=/etc/init.d/freeswitch

- name: Change ownership of FreeSwitch init script
  file: path=/etc/init.d/freeswitch owner={{freeswitch_owner}} group={{freeswitch_group}} mode="a+x"

- name: update init scripts
  shell: update-rc.d freeswitch defaults

- name: cli link
  file: src={{freeswitch_path}}bin/fs_cli dest=/bin/fs_cli state=link

- name: log files management
  copy: src={{ freeswicth_log_rotate_script }} dest=/etc/cron.daily/freeswitch_log_rotation

- shell: touch /var/log/freeswitch.log

- file: path=/var/log/freeswitch.log owner={{freeswitch_owner}} group={{freeswitch_group}}

- file: path=/etc/cron.daily/freeswitch_log_rotation mode="a+x"

- name: install fail2ban
  apt: name=fail2ban state=latest

- copy: src={{ fail2ban_local_jail }} dest={{ fail2ban_local_jail_file }}
- copy: src={{ fail2ban_fs }} dest={{ fail2ban_filter_dir }}/freeswitch.conf
- copy: src={{ fail2ban_dos_fs }} dest={{ fail2ban_filter_dir }}/freeswitch-dos.conf
